<?php
if(isset($_GET['name'])){
$name=$_GET['name'];
//if(file_exists($name)){
	$path="uploads/";
	$dir=$path.$name;
	header('Content-Description:File Transfer');
	header('Content-Type:application/octet-stream');
	header('Content-Disposition:attachment;filename='.basename($dir));
	header('Content-Transfer-Encoding:binary');
	header('Expires:0');
	header('Cache-Control:must-revalidate');
	header('Pragma:public');
	header('Content-Length:'.filesize($dir));
	ob_clean();
	flush();
	readfile($dir);
	exit;
//}
}
?>